import type {
  Integration,
  Insight,
  InsightStats,
  CustomerProfile,
  PrdAssessment,
  ShippedFeature,
} from "./types";

export const INTEGRATIONS: Integration[] = [
  {
    id: "posthog",
    name: "PostHog",
    category: "Analytics + Session Replay + Feature Flags",
    description: "Product analytics, session replay, and feature flags",
    connectedDate: "2025-10-15",
    dataSynced: ["Events", "Session Recordings", "Feature Flags", "Funnels"],
    status: "connected",
    iconColor: "#1D4AFF",
  },
  {
    id: "linear",
    name: "Linear",
    category: "Project Management",
    description: "Issue tracking and project management",
    connectedDate: "2025-10-12",
    dataSynced: ["Issues", "Projects", "Cycles", "Roadmap"],
    status: "connected",
    iconColor: "#5E6AD2",
  },
  {
    id: "notion",
    name: "Notion",
    category: "Docs & Knowledge",
    description: "Documentation, wikis, and user interview notes",
    connectedDate: "2025-10-18",
    dataSynced: ["Pages", "Databases", "Interview Notes"],
    status: "connected",
    iconColor: "#EFEFEF",
  },
  {
    id: "intercom",
    name: "Intercom",
    category: "Customer Support",
    description: "Customer conversations and support tickets",
    connectedDate: "2025-11-02",
    dataSynced: ["Conversations", "Tickets", "CSAT Scores"],
    status: "connected",
    iconColor: "#1F8DED",
  },
  {
    id: "hubspot",
    name: "HubSpot",
    category: "CRM",
    description: "Customer relationship management and sales pipeline",
    connectedDate: "2025-11-05",
    dataSynced: ["Contacts", "Deals", "Companies", "Tickets"],
    status: "connected",
    iconColor: "#FF7A59",
  },
  {
    id: "slack",
    name: "Slack",
    category: "Internal Communication",
    description: "Team messaging and internal feedback channels",
    connectedDate: "2025-10-12",
    dataSynced: ["#product-feedback", "#customer-issues", "#feature-requests"],
    status: "connected",
    iconColor: "#E01E5A",
  },
  {
    id: "github",
    name: "GitHub",
    category: "Version Control",
    description: "Repositories, PRs, and deployment tracking",
    connectedDate: "2025-10-12",
    dataSynced: ["Repositories", "Pull Requests", "Deployments", "Releases"],
    status: "connected",
    iconColor: "#F0F0F0",
  },
];

export const INSIGHT_STATS: InsightStats = {
  totalInsights: 23,
  criticalCount: 3,
  avgResolutionDays: 4.2,
  dataSourcesActive: 7,
};

export const INSIGHTS: Insight[] = [
  {
    id: "ins-1",
    title: "Agent policy violations spike during off-hours deployments",
    severity: "critical",
    sources: [
      { tool: "PostHog", detail: "Event spike: agent_policy_violation" },
      { tool: "Intercom", detail: "12 tickets mentioning 'unauthorized agent actions'" },
    ],
    description:
      "Deployments pushed between 9 PM and 6 AM trigger 3.2x more policy violation alerts than daytime deployments. Session replays show security teams are not monitoring the dashboard during these windows, causing a 47-minute average delay in response to critical violations.",
    proposedAction:
      "Add automated escalation rules for off-hours violations. Require mandatory human-in-the-loop approval for agent actions during low-staffing windows.",
    discoveredDate: "2026-02-19",
    affectedUsers: 34,
    confidence: 92,
  },
  {
    id: "ins-2",
    title: "Enterprise onboarding drop-off at agent permission configuration",
    severity: "critical",
    sources: [
      { tool: "PostHog", detail: "Funnel: 61% drop-off at step 3 of setup wizard" },
      { tool: "HubSpot", detail: "3 deals stalled at 'Technical Setup' stage" },
      { tool: "Notion", detail: "Interview note: 'permission model is confusing'" },
    ],
    description:
      "61% of new enterprise accounts abandon the setup wizard at the agent permission configuration step. Session replays reveal users cycling between the docs and the config page an average of 4 times. The permission model uses 14 granular toggles when most users need one of 3 common presets.",
    proposedAction:
      "Replace granular permission toggles with 3 preset templates (Restrictive, Balanced, Permissive) and an 'Advanced' expandable section. Add inline contextual help tooltips.",
    discoveredDate: "2026-02-17",
    affectedUsers: 61,
    confidence: 88,
  },
  {
    id: "ins-3",
    title: "Monitoring dashboard latency drives users to third-party tools",
    severity: "warning",
    sources: [
      { tool: "PostHog", detail: "p95 dashboard load: 8.2s (target: 2s)" },
      { tool: "Intercom", detail: "7 complaints about 'slow dashboard'" },
      { tool: "Slack", detail: "#customer-issues: Grafana screenshots shared as workaround" },
    ],
    description:
      "The real-time agent monitoring dashboard has a p95 load time of 8.2 seconds. Power users (security team leads) are bypassing Paladin entirely and building their own Grafana dashboards from our API, fragmenting the security view and creating audit gaps.",
    proposedAction:
      "Implement incremental data loading with skeleton states. Prioritize the 'Active Threats' panel to load first. Target p95 under 2 seconds within the next sprint.",
    discoveredDate: "2026-02-15",
    affectedUsers: 28,
    confidence: 85,
  },
  {
    id: "ins-4",
    title: "Support tickets reveal confusion between 'pause' and 'kill' agent actions",
    severity: "warning",
    sources: [
      { tool: "Intercom", detail: "18 tickets: 'I paused but agent kept running'" },
      { tool: "PostHog", detail: "Session replay: users clicking 'pause' then 'kill' within 30s" },
    ],
    description:
      "Users expect 'Pause Agent' to immediately halt all agent actions, but it only prevents new task assignment while letting current tasks complete. 18 support tickets in the last 30 days describe frustrated users who paused an agent that continued executing for up to 12 minutes.",
    proposedAction:
      "Rename to 'Stop New Tasks' vs 'Emergency Halt'. Add a confirmation modal for Emergency Halt explaining the difference. Update in-app tooltip copy.",
    discoveredDate: "2026-02-13",
    affectedUsers: 15,
    confidence: 79,
  },
  {
    id: "ins-5",
    title: "High-value accounts under-utilizing audit log exports",
    severity: "info",
    sources: [
      { tool: "PostHog", detail: "Feature flag: audit_export used by 12% of Enterprise tier" },
      { tool: "HubSpot", detail: "4 Enterprise accounts never activated compliance module" },
    ],
    description:
      "Only 12% of Enterprise-tier accounts are using the audit log export feature, despite compliance reporting being a top-3 stated purchase reason during sales calls. The feature is buried 3 clicks deep in Settings > Compliance > Export.",
    proposedAction:
      "Surface audit log export as a primary action in the sidebar. Add a 'Compliance Dashboard' section to the main navigation. Trigger an in-app prompt for Enterprise accounts that haven't exported in 30+ days.",
    discoveredDate: "2026-02-11",
    affectedUsers: 88,
    confidence: 71,
  },
];

export const CUSTOMER_PROFILES: CustomerProfile[] = [
  {
    id: "profile-1",
    name: "Sarah Chen",
    title: "Head of AI Security",
    company: "Large enterprise (1000+ employees), regulated industry",
    avatar: { initials: "SC", color: "#13DAEC" },
    jtbdStatements: [
      "I need to prove to our CISO that every AI agent action is auditable and compliant",
      "I want to catch policy violations before they become security incidents",
      "I need a single pane of glass for all agent activity across our 40+ deployed agents",
    ],
    prevalence: 38,
    satisfactionScore: 72,
    metrics: {
      avgSessionDuration: "34 min",
      weeklyActiveRate: 89,
      supportTicketsPerMonth: 2.1,
      churnRisk: "low",
      npsScore: 42,
    },
    topPainPoints: [
      "Dashboard load time makes real-time monitoring impractical",
      "Permission configuration is too granular for initial setup",
      "Audit export is hard to find when preparing compliance reports",
    ],
  },
  {
    id: "profile-2",
    name: "Marcus Rivera",
    title: "Platform Engineering Lead",
    company: "Mid-market tech company (200\u2013500 employees)",
    avatar: { initials: "MR", color: "#FFA500" },
    jtbdStatements: [
      "I want to deploy AI agents fast without worrying about security blowing up in production",
      "I need guardrails that don't slow down my development velocity",
      "I want to integrate Paladin into our existing CI/CD pipeline seamlessly",
    ],
    prevalence: 29,
    satisfactionScore: 65,
    metrics: {
      avgSessionDuration: "12 min",
      weeklyActiveRate: 64,
      supportTicketsPerMonth: 3.8,
      churnRisk: "medium",
      npsScore: 28,
    },
    topPainPoints: [
      "API documentation is incomplete for advanced use cases",
      "No native GitHub Actions integration for policy-as-code",
      "Pause vs kill agent confusion wastes debugging time",
    ],
  },
  {
    id: "profile-3",
    name: "Diana Okoro",
    title: "VP of Engineering",
    company: "Growth-stage startup (50\u2013200 employees), AI-first",
    avatar: { initials: "DO", color: "#A855F7" },
    jtbdStatements: [
      "I need to give my board confidence that our AI product is safe to scale",
      "I want visibility into agent behavior without hiring a dedicated security team",
      "I need SOC 2 compliance evidence without a 6-month project",
    ],
    prevalence: 22,
    satisfactionScore: 78,
    metrics: {
      avgSessionDuration: "8 min",
      weeklyActiveRate: 41,
      supportTicketsPerMonth: 1.2,
      churnRisk: "low",
      npsScore: 55,
    },
    topPainPoints: [
      "Pricing feels high for a startup with only 5 agents to monitor",
      "Setup wizard assumes enterprise-level security knowledge",
      "Would love a 'startup mode' with simplified defaults",
    ],
  },
  {
    id: "profile-4",
    name: "James Whitfield",
    title: "Security Operations Analyst",
    company: "Large enterprise, financial services",
    avatar: { initials: "JW", color: "#EF4444" },
    jtbdStatements: [
      "I need to respond to agent anomalies within my 5-minute SLA",
      "I want actionable alerts, not a firehose of false positives",
      "I need to understand what an agent did and WHY it violated policy",
    ],
    prevalence: 11,
    satisfactionScore: 58,
    metrics: {
      avgSessionDuration: "52 min",
      weeklyActiveRate: 95,
      supportTicketsPerMonth: 5.4,
      churnRisk: "high",
      npsScore: 12,
    },
    topPainPoints: [
      "Alert fatigue \u2014 too many low-severity notifications",
      "Cannot correlate agent actions with the triggering user request",
      "Off-hours violations lack automated escalation",
    ],
  },
];

export const PRD_ASSESSMENTS: PrdAssessment[] = [
  {
    id: "prd-1",
    title: "Automated Agent Quarantine on Policy Breach",
    status: "approved",
    linearTicket: "PAL-187",
    author: "Priya Sharma",
    overallFitness: 84,
    profileFitness: [
      { profileId: "profile-1", profileName: "Sarah Chen", score: 91, rationale: "Directly addresses her need for proactive violation response and audit trail" },
      { profileId: "profile-2", profileName: "Marcus Rivera", score: 78, rationale: "Valuable but he needs the quarantine to be configurable per-environment" },
      { profileId: "profile-3", profileName: "Diana Okoro", score: 82, rationale: "Board-level confidence builder; simple on/off is ideal for small teams" },
      { profileId: "profile-4", profileName: "James Whitfield", score: 95, rationale: "Critical for his 5-min SLA \u2014 automatic quarantine removes manual triage step" },
    ],
    keyStrengths: [
      "Clear problem definition backed by incident data",
      "Phased rollout reduces blast radius",
      "Strong alignment with 3 of 4 customer profiles",
    ],
    keyRisks: [
      "False positive quarantines could disrupt production workloads",
      "No rollback mechanism defined for wrongful quarantine",
      "Depends on policy engine accuracy which is currently at 94.2%",
    ],
    lastUpdated: "2026-02-18",
  },
  {
    id: "prd-2",
    title: "Agent Behavior Explainability Dashboard",
    status: "under_review",
    linearTicket: "PAL-203",
    author: "Tom Reyes",
    overallFitness: 71,
    profileFitness: [
      { profileId: "profile-1", profileName: "Sarah Chen", score: 68, rationale: "Useful for audits but she needs export capability which is not included" },
      { profileId: "profile-2", profileName: "Marcus Rivera", score: 55, rationale: "Low priority \u2014 he cares more about CI/CD integration than dashboards" },
      { profileId: "profile-3", profileName: "Diana Okoro", score: 83, rationale: "High value for board reporting; visual explainability is a differentiator" },
      { profileId: "profile-4", profileName: "James Whitfield", score: 92, rationale: "Addresses his top pain point of understanding WHY violations happened" },
    ],
    keyStrengths: [
      "Unique differentiator \u2014 no competitor offers agent decision tracing",
      "Strong user interview signal (mentioned in 8 of 12 recent interviews)",
    ],
    keyRisks: [
      "Scope is vague \u2014 'explainability' means different things to different profiles",
      "Performance risk: tracing adds latency to agent execution",
      "No clear success metrics defined in the PRD",
    ],
    lastUpdated: "2026-02-20",
  },
  {
    id: "prd-3",
    title: "Slack-Native Alert Triage Workflow",
    status: "needs_revision",
    linearTicket: "PAL-211",
    author: "Kim Nakamura",
    overallFitness: 52,
    profileFitness: [
      { profileId: "profile-1", profileName: "Sarah Chen", score: 45, rationale: "Security-conscious; prefers actions in Paladin UI for audit trail, not Slack" },
      { profileId: "profile-2", profileName: "Marcus Rivera", score: 72, rationale: "Already lives in Slack; would reduce context-switching significantly" },
      { profileId: "profile-3", profileName: "Diana Okoro", score: 48, rationale: "Small team already uses Paladin directly; Slack adds a layer, not simplicity" },
      { profileId: "profile-4", profileName: "James Whitfield", score: 38, rationale: "Needs structured triage, not chat-based workflows; audit trail concerns" },
    ],
    keyStrengths: [
      "Meets developers where they already work",
      "Could reduce time-to-acknowledge for non-critical alerts",
    ],
    keyRisks: [
      "Fragmenting the security workflow across two interfaces",
      "Actions taken in Slack may not produce compliant audit logs",
      "Only addresses Marcus's profile well; misaligned with 3 of 4 profiles",
      "No competitive data on whether Slack-native security tools retain users",
    ],
    lastUpdated: "2026-02-21",
  },
];

export const SHIPPED_FEATURES: ShippedFeature[] = [
  {
    id: "feat-1",
    name: "Real-Time Agent Activity Feed",
    description: "Live-updating feed showing all agent actions, decisions, and state changes across monitored agents",
    linearTicket: "PAL-098",
    launchDate: "2025-12-04",
    developmentDays: 18,
    status: "exceeding",
    metrics: [
      { name: "Daily Active Users", targetValue: "340", baselineValue: "0", actualValue: "412", unit: "users", trend: "up", isPositive: true },
      { name: "Avg. Time to Detect Anomaly", targetValue: "< 8 min", baselineValue: "23 min", actualValue: "5.2 min", unit: "", trend: "down", isPositive: true },
      { name: "Dashboard Engagement", targetValue: "15 min/session", baselineValue: "6 min/session", actualValue: "22 min/session", unit: "", trend: "up", isPositive: true },
    ],
    githubPrs: 14,
    contributors: ["Priya S.", "Alex K.", "Jordan M."],
  },
  {
    id: "feat-2",
    name: "Policy-as-Code Engine v2",
    description: "Declarative YAML-based policy definitions with version control and dry-run testing",
    linearTicket: "PAL-112",
    launchDate: "2026-01-09",
    developmentDays: 24,
    status: "on_track",
    metrics: [
      { name: "Policies Created", targetValue: "200", baselineValue: "0", actualValue: "187", unit: "policies", trend: "up", isPositive: true },
      { name: "Policy Eval Latency", targetValue: "< 50ms", baselineValue: "120ms (v1)", actualValue: "38ms", unit: "", trend: "down", isPositive: true },
      { name: "False Positive Rate", targetValue: "< 5%", baselineValue: "11.3%", actualValue: "4.8%", unit: "", trend: "down", isPositive: true },
    ],
    githubPrs: 22,
    contributors: ["Tom R.", "Priya S.", "Kim N.", "Alex K."],
  },
  {
    id: "feat-3",
    name: "Multi-Tenant Agent Isolation",
    description: "Workspace-level agent sandboxing ensuring one tenant's agents cannot access another tenant's data",
    linearTicket: "PAL-134",
    launchDate: "2026-01-28",
    developmentDays: 31,
    status: "on_track",
    metrics: [
      { name: "Enterprise Deals Unblocked", targetValue: "5", baselineValue: "0", actualValue: "4", unit: "deals", trend: "up", isPositive: true },
      { name: "Isolation Breaches Caught", targetValue: "100%", baselineValue: "N/A", actualValue: "100%", unit: "", trend: "flat", isPositive: true },
      { name: "Tenant Provisioning Time", targetValue: "< 2 min", baselineValue: "15 min (manual)", actualValue: "1.4 min", unit: "", trend: "down", isPositive: true },
    ],
    githubPrs: 19,
    contributors: ["Alex K.", "Jordan M."],
  },
  {
    id: "feat-4",
    name: "Automated Compliance Report Generator",
    description: "One-click SOC 2 and ISO 27001 evidence collection from agent audit logs",
    linearTicket: "PAL-156",
    launchDate: "2026-02-11",
    developmentDays: 15,
    status: "underperforming",
    metrics: [
      { name: "Reports Generated", targetValue: "50/week", baselineValue: "0", actualValue: "18/week", unit: "", trend: "up", isPositive: false },
      { name: "Accounts Using Feature", targetValue: "30%", baselineValue: "0%", actualValue: "12%", unit: "of Enterprise", trend: "up", isPositive: false },
      { name: "Manual Report Time Saved", targetValue: "4 hrs/report", baselineValue: "6 hrs (manual)", actualValue: "3.8 hrs saved", unit: "", trend: "down", isPositive: true },
    ],
    githubPrs: 8,
    contributors: ["Kim N.", "Tom R."],
  },
];
